// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-monitored.js` after changing api/_shared/sources.js.
//
// Companies Promptly pulls automatically from the employer's own job system.
// The app uses this to avoid promising an alert for an employer whose postings
// we cannot actually read, and /how-it-works publishes these counts so the
// public numbers are always the real ones.
window.MONITORED_COMPANIES = [
  "AbbVie",
  "Adidas",
  "Adobe",
  "Affirm",
  "Airbnb",
  "Airtable",
  "Akuna Capital",
  "AllianceBernstein",
  "American Express",
  "American Red Cross",
  "American Securities",
  "Ameriprise Financial",
  "Amgen",
  "Amplitude",
  "Anduril Industries",
  "Antares Capital",
  "Anthropic",
  "Apollo Global Management",
  "AQR Capital",
  "Aquatic Capital Management",
  "Ares Management",
  "Arrowstreet Capital",
  "Artisan Partners",
  "Asana",
  "Audax Private Equity",
  "Axios",
  "Bain Capital",
  "Baird",
  "Balyasny",
  "Benchling",
  "Betterment",
  "Biogen",
  "BlackRock",
  "Blackstone",
  "Blend",
  "Block",
  "Blue Origin",
  "Blue Owl",
  "Boeing",
  "Booz Allen Hamilton",
  "Bottomline Technologies",
  "Bread Financial",
  "Brex",
  "Bristol Myers Squibb",
  "Broadridge Financial",
  "Brookings Institution",
  "Capital One",
  "Carlyle",
  "Caterpillar",
  "Charles River Associates",
  "Charles Schwab",
  "Checkr",
  "Chicago Trading (CTC)",
  "Chime",
  "Cigna",
  "Citadel",
  "Citi",
  "Citizens",
  "Cloudflare",
  "CockroachDB",
  "Code for America",
  "Cohere",
  "Coinbase",
  "Colliers",
  "Comcast NBCUniversal",
  "Continental",
  "Coursera",
  "Cravath",
  "CrowdStrike",
  "Cursor (Anysphere)",
  "Cushman & Wakefield",
  "CVS Health",
  "D. E. Shaw",
  "Databricks",
  "Datadog",
  "Davis Polk",
  "Dentsu",
  "Discord",
  "Disney",
  "Doctors Without Borders",
  "Dodge & Cox",
  "DoorDash",
  "Dropbox",
  "DRW",
  "Duolingo",
  "DV Trading",
  "Elastic",
  "ElevenLabs",
  "Ellipsis Labs",
  "Enova International",
  "Epic Games",
  "Estée Lauder",
  "ExodusPoint",
  "Experian",
  "Federal Reserve Board",
  "Fifth Third Bank",
  "Figma",
  "FIS",
  "Fiserv",
  "Five Rings",
  "Flatiron Health",
  "Flow Traders",
  "Ford",
  "Fox",
  "Franklin Templeton",
  "FS Investments",
  "Gates Foundation",
  "GE Appliances",
  "Gelber Group",
  "Genentech",
  "General Atlantic",
  "General Mills",
  "Geneva Trading",
  "Gibson Dunn",
  "Gilead Sciences",
  "Ginkgo Bioworks",
  "GitLab",
  "Glossier",
  "Goldman Sachs",
  "Gopuff",
  "GSK",
  "GTCR",
  "Guggenheim Investments",
  "Guggenheim Securities",
  "Guidehouse",
  "Gusto",
  "Habitat for Humanity",
  "Harvey",
  "Headway",
  "Hearst",
  "Holocene Advisors",
  "Houlihan Lokey",
  "Howard Hughes (HHMI)",
  "Hudson River Trading",
  "Humana",
  "Huntington Bank",
  "Huron",
  "Illumina",
  "IMC Trading",
  "Insitro",
  "Instacart",
  "Intel",
  "Interactive Brokers",
  "Invesco",
  "Jane Street",
  "JLL",
  "Johnson & Johnson",
  "Jones Day",
  "JPMorgan",
  "Jump Trading",
  "KeyBank",
  "Keystone Strategy",
  "Khan Academy",
  "Kirkland & Ellis",
  "KKR",
  "Komodo Health",
  "Kraft Heinz",
  "L'Oréal",
  "Latham & Watkins",
  "LaunchDarkly",
  "Leidos",
  "LendingClub",
  "Lincoln International",
  "Linear",
  "LionTree",
  "Live Nation",
  "LiveRamp",
  "LoanCore Capital",
  "Lone Pine Capital",
  "Lord Abbett",
  "Lucid Motors",
  "Lyft",
  "M&T Bank",
  "Man Group",
  "Marshall Wace",
  "MassMutual",
  "Mastercard",
  "Merck",
  "Millennium",
  "Mixpanel",
  "Modal",
  "Moderna",
  "Moelis",
  "Mondelez",
  "MongoDB",
  "Natera",
  "NBA",
  "Netflix",
  "Netic",
  "Neuberger Berman",
  "Neuralink",
  "Nike",
  "Northern Trust",
  "Northrop Grumman",
  "Notion",
  "Novartis",
  "Nubank",
  "Nuro",
  "Nuveen",
  "Nvidia",
  "Ogilvy",
  "Okta",
  "Old Mission",
  "OpenAI",
  "Optiver",
  "Oscar Health",
  "Palantir",
  "Paramount",
  "Patreon",
  "Paul, Weiss",
  "PDT Partners",
  "Peloton",
  "PepsiCo",
  "Pfizer",
  "PGIM",
  "PIMCO",
  "Pinterest",
  "Piper Sandler",
  "PJT Partners",
  "Plaid",
  "PNC Financial Services",
  "Point72",
  "Postman",
  "Procter & Gamble",
  "Prologis",
  "Prosper Marketplace",
  "Qualcomm",
  "Ramp",
  "RAND Corporation",
  "Raymond James",
  "Recursion",
  "Reddit",
  "Regions Bank",
  "Relativity Space",
  "Replit",
  "Riot Games",
  "Roark Capital Group",
  "Robinhood",
  "Roblox",
  "Roche",
  "Rocket Lab",
  "Roland Berger",
  "Rothschild & Co",
  "Salesforce",
  "Samsara",
  "Sanofi",
  "Scale AI",
  "Schonfeld",
  "ServiceNow",
  "Shield AI",
  "Sidley Austin",
  "Sierra",
  "Simpson Thacher",
  "Sixth Street",
  "Skadden",
  "Skydio",
  "Snowflake",
  "SoFi",
  "Solar Turbines",
  "Sony Pictures",
  "SpaceX",
  "Spotify",
  "Squarepoint Capital",
  "Squarespace",
  "State Street",
  "Stifel",
  "Stripe",
  "Substack",
  "Sullivan & Cromwell",
  "Supabase",
  "Susquehanna (SIG)",
  "Sweetgreen",
  "Synchrony",
  "T. Rowe Price",
  "Target",
  "Teach For America",
  "Temenos",
  "The Athletic",
  "The New York Times",
  "The Trade Desk",
  "ThoughtWorks",
  "Toast",
  "Tower Research Capital",
  "TPG",
  "TransMarket Group",
  "Truist",
  "Twitch",
  "Two Sigma",
  "U.S. Bank",
  "U.S. Federal Government",
  "Uber",
  "Ubisoft",
  "Udemy",
  "Unilever",
  "Vanguard",
  "Vanta",
  "Vatic Labs",
  "Vercel",
  "Verition",
  "Vertex Pharmaceuticals",
  "Virtu Financial",
  "Visa",
  "Voloridge Investment Management",
  "Vox Media",
  "VTS",
  "Walleye Capital",
  "Warner Bros. Discovery",
  "Wasserman",
  "Waymo",
  "Webflow",
  "Wellington Management",
  "Western Digital",
  "White & Case",
  "Wikimedia Foundation",
  "William Blair",
  "Winton",
  "Workday",
  "WPP",
  "Writer",
  "Zillow",
  "Zipline",
  "Zocdoc",
  "Zoox"
];

window.PROMPTLY_COVERAGE = {
  "sources": 323,
  "companies": 323,
  "byPlatform": {
    "greenhouse": 133,
    "custom": 45,
    "workday": 91,
    "lever": 7,
    "ashby": 25,
    "smartrecruiters": 9,
    "florecruit": 11,
    "usajobs": 1,
    "taleo": 1
  },
  "byField": {
    "Finance": 130,
    "Technology": 66,
    "Consulting": 7,
    "Healthcare": 29,
    "Education": 4,
    "Engineering": 20,
    "Media": 15,
    "Consumer": 15,
    "Nonprofit": 7,
    "Sports": 3,
    "Real Estate": 6,
    "Law": 13,
    "Government": 4,
    "Marketing": 3,
    "Science": 1
  }
};
