// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-monitored.js` after changing api/_shared/sources.js.
//
// Companies Promptly pulls automatically from the employer's own job system.
// The app uses this to avoid promising an alert for an employer whose postings
// we cannot actually read.
window.MONITORED_COMPANIES = [
  "Adobe",
  "Affirm",
  "Airbnb",
  "Airtable",
  "Akuna Capital",
  "Amplitude",
  "Anduril Industries",
  "Anthropic",
  "Ares Management",
  "Asana",
  "Atlassian",
  "Bain Capital",
  "Betterment",
  "Blackstone",
  "Boeing",
  "Brex",
  "Charles River Associates",
  "Checkr",
  "Chicago Trading (CTC)",
  "Chime",
  "Cloudflare",
  "CockroachDB",
  "Code for America",
  "Cohere",
  "Coinbase",
  "Comcast NBCUniversal",
  "Continental",
  "Coursera",
  "Cursor (Anysphere)",
  "CVS Health",
  "Databricks",
  "Datadog",
  "Discord",
  "DoorDash",
  "Dropbox",
  "DRW",
  "Duolingo",
  "Elastic",
  "ElevenLabs",
  "Epic Games",
  "Experian",
  "Figma",
  "Five Rings",
  "Flatiron Health",
  "Flow Traders",
  "General Atlantic",
  "Ginkgo Bioworks",
  "GitLab",
  "Glossier",
  "Guggenheim Securities",
  "Gusto",
  "Harvey",
  "Houlihan Lokey",
  "IMC Trading",
  "Instacart",
  "Jane Street",
  "Jump Trading",
  "Keystone Strategy",
  "Khan Academy",
  "Komodo Health",
  "LaunchDarkly",
  "Linear",
  "Lyft",
  "Marshall Wace",
  "Mixpanel",
  "Modal",
  "MongoDB",
  "Netflix",
  "Northrop Grumman",
  "Notion",
  "Nubank",
  "Nvidia",
  "Okta",
  "Old Mission",
  "OpenAI",
  "Optiver",
  "Oscar Health",
  "Palantir",
  "PDT Partners",
  "Peloton",
  "Pinterest",
  "Point72",
  "Postman",
  "Ramp",
  "Recursion",
  "Reddit",
  "Relativity Space",
  "Replit",
  "Riot Games",
  "Robinhood",
  "Roblox",
  "Rocket Lab",
  "Salesforce",
  "Samsara",
  "Scale AI",
  "Schonfeld",
  "ServiceNow",
  "Sierra",
  "SoFi",
  "SpaceX",
  "Spotify",
  "Squarepoint Capital",
  "Squarespace",
  "Stripe",
  "Supabase",
  "Sweetgreen",
  "Target",
  "The Athletic",
  "The New York Times",
  "ThoughtWorks",
  "Toast",
  "Twitch",
  "U.S. Federal Government",
  "Ubisoft",
  "Udemy",
  "Vanta",
  "Vatic Labs",
  "Vercel",
  "Visa",
  "Vox Media",
  "VTS",
  "Webflow",
  "Wikimedia Foundation",
  "Writer",
  "Zipline",
  "Zocdoc"
];
