// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-monitored.js` after changing api/_shared/sources.js.
//
// Companies Promptly pulls automatically from the employer's own job system.
// The app uses this to avoid promising an alert for an employer whose postings
// we cannot actually read, and /how-it-works publishes these counts so the
// public numbers are always the real ones.
window.MONITORED_COMPANIES = [
  "AbbVie",
  "Accordion",
  "Adidas",
  "Adobe",
  "Affirm",
  "AIG",
  "Airbnb",
  "Airtable",
  "AKQA",
  "Akuna Capital",
  "AlixPartners",
  "AllianceBernstein",
  "AlphaSights",
  "American Express",
  "American Red Cross",
  "American Securities",
  "Ameriprise Financial",
  "Amgen",
  "Amplitude",
  "Andela",
  "Anduril Industries",
  "Anomaly",
  "Antares Capital",
  "Anthropic",
  "Apollo Global Management",
  "AQR Capital",
  "Aquatic Capital Management",
  "Ares Management",
  "Arrowstreet Capital",
  "Artisan Partners",
  "Asana",
  "Audax Private Equity",
  "Axios",
  "Bain Capital",
  "Baird",
  "Baker Tilly",
  "Balyasny",
  "Bank of America",
  "Barbarian",
  "Barclays",
  "Barnes & Thornburg",
  "BCG",
  "BDO",
  "Benchling",
  "Bessemer Venture Partners",
  "Betterment",
  "Bill.com",
  "Biogen",
  "BitGo",
  "BlackRock",
  "Blackstone",
  "Blend",
  "Block",
  "Blue Origin",
  "Blue Owl",
  "BMO",
  "BNY Mellon",
  "Boeing",
  "Booz Allen Hamilton",
  "Bottomline Technologies",
  "Bounteous",
  "Bread Financial",
  "Brex",
  "Bristol Myers Squibb",
  "Broadridge Financial",
  "Brookings Institution",
  "Cantor Fitzgerald",
  "Capital Group",
  "Capital One",
  "Carlyle",
  "Carta",
  "Catalant",
  "Caterpillar",
  "Charles River Associates",
  "Charles Schwab",
  "Checkr",
  "Chicago Trading (CTC)",
  "Chime",
  "Chubb",
  "Cigna",
  "Citadel",
  "Citi",
  "Citizens",
  "ClearView Healthcare Partners",
  "Cleveland Clinic",
  "Cloudflare",
  "CME Group",
  "Coca-Cola",
  "CockroachDB",
  "Code and Theory",
  "Code for America",
  "Cohere",
  "Coinbase",
  "Colliers",
  "Comcast NBCUniversal",
  "Continental",
  "Cornerstone Research",
  "Coursera",
  "Cravath",
  "Critical Mass",
  "CrowdStrike",
  "Cursor (Anysphere)",
  "Cushman & Wakefield",
  "CVS Health",
  "D. E. Shaw",
  "Databricks",
  "Datadog",
  "Davis Polk",
  "Definitive Healthcare",
  "Dentsu",
  "Discord",
  "Disney",
  "DLR Group",
  "Doctors Without Borders",
  "Dodge & Cox",
  "DoorDash",
  "Dropbox",
  "DRW",
  "Duolingo",
  "DV Trading",
  "Edward Jones",
  "Elastic",
  "ElevenLabs",
  "Ellipsis Labs",
  "Enova International",
  "Epic Games",
  "Estée Lauder",
  "Evercore",
  "ExodusPoint",
  "Experian",
  "ExxonMobil",
  "EY",
  "FactSet",
  "Fanatics",
  "Federal Reserve Board",
  "Fidelity",
  "Fifth Third Bank",
  "Figma",
  "Fireblocks",
  "FIS",
  "Fiserv",
  "Five Rings",
  "Flatiron Health",
  "Flow Traders",
  "Ford",
  "Forrester",
  "Forvis Mazars",
  "Fox",
  "Franklin Templeton",
  "Frazier & Deeter",
  "FS Investments",
  "FSG",
  "Gates Foundation",
  "GE Appliances",
  "Gelber Group",
  "Gemini",
  "Genentech",
  "General Atlantic",
  "General Catalyst",
  "General Mills",
  "Geneva Trading",
  "Genpact",
  "Gibson Dunn",
  "Gilead Sciences",
  "Ginkgo Bioworks",
  "GitLab",
  "Glossier",
  "Goldman Sachs",
  "Golub Capital",
  "Gopuff",
  "Grant Thornton",
  "Graphite",
  "Grassi",
  "Green Dot",
  "GREY",
  "GSK",
  "GTCR",
  "Guggenheim Investments",
  "Guggenheim Securities",
  "Guidehouse",
  "Guidepoint",
  "Gusto",
  "Habitat for Humanity",
  "Harris Williams",
  "Harvey",
  "HCVT",
  "Headway",
  "Hearst",
  "Holocene Advisors",
  "Houlihan Lokey",
  "Howard Hughes (HHMI)",
  "Hudson River Trading",
  "Huge",
  "Humana",
  "Huntington Bank",
  "Huron",
  "Illumina",
  "IMC Trading",
  "Insight Partners",
  "Insitro",
  "Instacart",
  "Instrument",
  "Intel",
  "Interactive Brokers",
  "Interbrand",
  "Invesco",
  "Jane Street",
  "Jefferies",
  "JLL",
  "Johnson & Johnson",
  "Jones Day",
  "JPMorgan",
  "Jump Trading",
  "KeyBank",
  "Keystone Strategy",
  "Khan Academy",
  "Kirkland & Ellis",
  "KKR",
  "Komodo Health",
  "Kraft Heinz",
  "Kreischer Miller",
  "Kyriba",
  "L.E.K. Consulting",
  "L'Oréal",
  "Landor",
  "Latham & Watkins",
  "LaunchDarkly",
  "Lazard",
  "Leidos",
  "LendingClub",
  "Lincoln International",
  "Linear",
  "LionTree",
  "Live Nation",
  "LiveRamp",
  "LoanCore Capital",
  "Lone Pine Capital",
  "Lord Abbett",
  "Lucid Motors",
  "Lyft",
  "M&T Bank",
  "Man Group",
  "Marakon",
  "Marqeta",
  "Marshall Wace",
  "MassMutual",
  "Mastercard",
  "Mayo Clinic",
  "McKinsey & Company",
  "Merck",
  "Mercury",
  "MetLife",
  "MFS Investment Management",
  "Millennium",
  "Mintel",
  "Mixpanel",
  "Mizuho",
  "Modal",
  "Moderna",
  "Moelis",
  "Mondelez",
  "MongoDB",
  "Morgan Stanley",
  "Morning Consult",
  "Morningstar",
  "MUFG",
  "Nasdaq",
  "Natera",
  "NBA",
  "nCino",
  "Netflix",
  "Netic",
  "Neuberger Berman",
  "Neuralink",
  "NFL",
  "Nike",
  "Northern Trust",
  "Northrop Grumman",
  "Northwestern Mutual",
  "Notion",
  "Novartis",
  "Nubank",
  "Nuro",
  "Nuveen",
  "Nvidia",
  "Ogilvy",
  "Okta",
  "Old Mission",
  "OLIVER Agency",
  "OpenAI",
  "OppFi",
  "Optiver",
  "Oscar Health",
  "Palantir",
  "Paramount",
  "Pariveda",
  "Patreon",
  "Paul, Weiss",
  "PayPal",
  "PDT Partners",
  "Peloton",
  "PepsiCo",
  "Perr&Knight",
  "Pfizer",
  "PGIM",
  "PIMCO",
  "Pinterest",
  "Piper Sandler",
  "PJT Partners",
  "Plaid",
  "PNC Financial Services",
  "Point B",
  "Point72",
  "Postman",
  "Procter & Gamble",
  "Prologis",
  "Propeller Consulting",
  "Prophet",
  "Prosper Marketplace",
  "Protiviti",
  "Prudential Financial",
  "Qualcomm",
  "Ramp",
  "RAND Corporation",
  "Raymond James",
  "RBC",
  "Recursion",
  "Reddit",
  "Regions Bank",
  "Relativity Space",
  "Replit",
  "Riot Games",
  "Ripple",
  "Riveron",
  "Roark Capital Group",
  "Robinhood",
  "Roblox",
  "Roche",
  "Rocket Lab",
  "Roland Berger",
  "Rothschild & Co",
  "RSM",
  "RTX (Raytheon)",
  "Salesforce",
  "Samsara",
  "Sanofi",
  "Scale AI",
  "Schneider Downs",
  "Schonfeld",
  "Sculptor Capital",
  "ServiceNow",
  "Shield AI",
  "Sidley Austin",
  "Sierra",
  "Simpson Thacher",
  "Sixth Street",
  "Skadden",
  "Skydio",
  "Snowflake",
  "SoFi",
  "Solar Turbines",
  "Sony Pictures",
  "SpaceX",
  "Spotify",
  "Squarepoint Capital",
  "Squarespace",
  "SS&C Technologies",
  "State Street",
  "Stifel",
  "Stripe",
  "Substack",
  "Sullivan & Cromwell",
  "Supabase",
  "Susquehanna (SIG)",
  "Sweetgreen",
  "Synchrony",
  "Synovus",
  "T. Rowe Price",
  "Target",
  "Teach For America",
  "Temenos",
  "The Athletic",
  "The Brattle Group",
  "The New York Times",
  "The Trade Desk",
  "Third Bridge",
  "Thoma Bravo",
  "ThoughtWorks",
  "Toast",
  "Toptal",
  "Tower Research Capital",
  "TPG",
  "Trace3",
  "TransMarket Group",
  "Travelers",
  "Truist",
  "Turing",
  "Twitch",
  "Two Sigma",
  "U.S. Bank",
  "U.S. Federal Government",
  "Uber",
  "Ubisoft",
  "UBS",
  "Udemy",
  "Unilever",
  "Vaco",
  "Vanguard",
  "Vanta",
  "Vatic Labs",
  "Vercel",
  "Verition",
  "Vertex Pharmaceuticals",
  "Viget",
  "Virtu Financial",
  "Visa",
  "VML",
  "Voloridge Investment Management",
  "Vox Media",
  "VTS",
  "Walleye Capital",
  "Warner Bros. Discovery",
  "Wasserman",
  "Waymo",
  "Wealthfront",
  "Webflow",
  "Wellington Management",
  "Wells Fargo",
  "West Monroe",
  "Western Digital",
  "WEX",
  "White & Case",
  "Wikimedia Foundation",
  "William Blair",
  "Winton",
  "Woolpert",
  "Workday",
  "WPP",
  "Writer",
  "Zeta Global",
  "Zillow",
  "Zipline",
  "Zocdoc",
  "Zoox"
];

window.PROMPTLY_COVERAGE = {
  "sources": 444,
  "companies": 444,
  "byPlatform": {
    "greenhouse": 181,
    "custom": 71,
    "workday": 119,
    "lever": 17,
    "ashby": 34,
    "smartrecruiters": 9,
    "florecruit": 11,
    "usajobs": 1,
    "taleo": 1
  },
  "byField": {
    "Finance": 182,
    "Technology": 69,
    "Consulting": 47,
    "Healthcare": 32,
    "Education": 4,
    "Engineering": 24,
    "Law": 14,
    "Media": 15,
    "Consumer": 16,
    "Nonprofit": 7,
    "Sports": 5,
    "Real Estate": 6,
    "Government": 4,
    "Marketing": 18,
    "Science": 1
  }
};
