// ─────────────────────────────────────────────────────────────────────────
// Company watch-list (directory).
//
// These are firms Promptly TRACKS. They render as cards even before a real
// 2027 posting exists — shown as "Awaiting 2027 posting" (honest: we're
// watching, nothing live yet). The moment the live pipeline finds a real
// posting for one, the card flips to the verified listing automatically and
// the placeholder disappears. No fake links, ever.
//
// field/subField drive the filters. logo files live in assets/logos/<slug>.png
// (missing logos fall back to a clean colored tile).
// ─────────────────────────────────────────────────────────────────────────
window.WATCHLIST = [
  // ── Payments / card networks ─────────────────────────────────────────────
  { company: "Visa", short: "V", field: "Finance", subField: "Payments", logo: "assets/logos/visa.png" },
  { company: "Mastercard", short: "MA", field: "Finance", subField: "Payments", logo: "assets/logos/mastercard.png" },
  { company: "PayPal", short: "PYPL", field: "Finance", subField: "Payments", logo: "assets/logos/paypal.png" },
  { company: "American Express", short: "AXP", field: "Finance", subField: "Payments", logo: "assets/logos/amex.png" },
  { company: "Discover Financial", short: "DFS", field: "Finance", subField: "Payments", logo: "assets/logos/discover.png" },
  { company: "Block (Square)", short: "XYZ", field: "Finance", subField: "Payments", logo: "assets/logos/block.png" },
  { company: "Green Dot", short: "GDOT", field: "Finance", subField: "Payments", logo: "assets/logos/greendot.png" },
  { company: "Marqeta", short: "MQ", field: "Finance", subField: "Payments", logo: "assets/logos/marqeta.png" },

  // ── Fintech / lending / financial software ───────────────────────────────
  { company: "Synchrony Financial", short: "SYF", field: "Finance", subField: "Fintech", logo: "assets/logos/synchrony.png" },
  { company: "Bread Financial", short: "BFH", field: "Finance", subField: "Fintech", logo: "assets/logos/breadfinancial.png" },
  { company: "Klarna", short: "KLAR", field: "Finance", subField: "Fintech", logo: "assets/logos/klarna.png" },
  { company: "Plaid", short: "PLD", field: "Finance", subField: "Fintech", logo: "assets/logos/plaid.png" },
  { company: "nCino", short: "NCNO", field: "Finance", subField: "Fintech", logo: "assets/logos/ncino.png" },
  { company: "Blend", short: "BLND", field: "Finance", subField: "Fintech", logo: "assets/logos/blend.png" },
  { company: "Enova International", short: "ENVA", field: "Finance", subField: "Fintech", logo: "assets/logos/enova.png" },
  { company: "OppFi", short: "OPFI", field: "Finance", subField: "Fintech", logo: "assets/logos/oppfi.png" },
  { company: "LendingClub", short: "LC", field: "Finance", subField: "Fintech", logo: "assets/logos/lendingclub.png" },
  { company: "Prosper Marketplace", short: "PRSP", field: "Finance", subField: "Fintech", logo: "assets/logos/prosper.png" },
  { company: "Morningstar", short: "MORN", field: "Finance", subField: "Fintech", logo: "assets/logos/morningstar.png" },
  { company: "FactSet", short: "FDS", field: "Finance", subField: "Fintech", logo: "assets/logos/factset.png" },
  { company: "Broadridge Financial", short: "BR", field: "Finance", subField: "Fintech", logo: "assets/logos/broadridge.png" },
  { company: "SS&C Technologies", short: "SSNC", field: "Finance", subField: "Fintech", logo: "assets/logos/ssctech.png" },
  { company: "FIS Global", short: "FIS", field: "Finance", subField: "Fintech", logo: "assets/logos/fisglobal.png" },
  { company: "Fiserv", short: "FI", field: "Finance", subField: "Fintech", logo: "assets/logos/fiserv.png" },
  { company: "Jack Henry & Associates", short: "JKHY", field: "Finance", subField: "Fintech", logo: "assets/logos/jackhenry.png" },
  { company: "Temenos", short: "TEMN", field: "Finance", subField: "Fintech", logo: "assets/logos/temenos.png" },
  { company: "Bottomline Technologies", short: "EPAY", field: "Finance", subField: "Fintech", logo: "assets/logos/bottomline.png" },
  { company: "Kyriba", short: "KYRB", field: "Finance", subField: "Fintech", logo: "assets/logos/kyriba.png" },

  // ── Private equity ───────────────────────────────────────────────────────
  { company: "Apollo Global Management", short: "APO", field: "Finance", subField: "Private Equity", logo: "assets/logos/apollo.png" },
  { company: "KKR", short: "KKR", field: "Finance", subField: "Private Equity", logo: "assets/logos/kkr.png" },
  { company: "Carlyle Group", short: "CG", field: "Finance", subField: "Private Equity", logo: "assets/logos/carlyle.png" },
  { company: "Warburg Pincus", short: "WP", field: "Finance", subField: "Private Equity", logo: "assets/logos/warburgpincus.png" },
  { company: "TPG", short: "TPG", field: "Finance", subField: "Private Equity", logo: "assets/logos/tpg.png" },
  { company: "Advent International", short: "ADV", field: "Finance", subField: "Private Equity", logo: "assets/logos/advent.png" },
  { company: "Vista Equity Partners", short: "VISTA", field: "Finance", subField: "Private Equity", logo: "assets/logos/vista.png" },
  { company: "Francisco Partners", short: "FP", field: "Finance", subField: "Private Equity", logo: "assets/logos/franciscopartners.png" },
  { company: "Silver Lake", short: "SL", field: "Finance", subField: "Private Equity", logo: "assets/logos/silverlake.png" },
  { company: "Madison Dearborn", short: "MDP", field: "Finance", subField: "Private Equity", logo: "assets/logos/mdcp.png" },
  { company: "GTCR", short: "GTCR", field: "Finance", subField: "Private Equity", logo: "assets/logos/gtcr.png" },
  { company: "Riverside Company", short: "RIV", field: "Finance", subField: "Private Equity", logo: "assets/logos/riverside.png" },
  { company: "Audax Private Equity", short: "AUD", field: "Finance", subField: "Private Equity", logo: "assets/logos/audax.png" },
  { company: "Summit Partners", short: "SMT", field: "Finance", subField: "Private Equity", logo: "assets/logos/summitpartners.png" },
  { company: "Leonard Green & Partners", short: "LGP", field: "Finance", subField: "Private Equity", logo: "assets/logos/leonardgreen.png" },
  { company: "Thoma Bravo", short: "TB", field: "Finance", subField: "Private Equity", logo: "assets/logos/thomabravo.png" },
  { company: "Roark Capital Group", short: "ROARK", field: "Finance", subField: "Private Equity", logo: "assets/logos/roark.png" },
  { company: "Welsh Carson", short: "WCAS", field: "Finance", subField: "Private Equity", logo: "assets/logos/welshcarson.png" },
  { company: "Thomas H. Lee Partners", short: "THL", field: "Finance", subField: "Private Equity", logo: "assets/logos/thl.png" },
  { company: "American Securities", short: "AS", field: "Finance", subField: "Private Equity", logo: "assets/logos/americansecurities.png" },
  { company: "Genstar Capital", short: "GEN", field: "Finance", subField: "Private Equity", logo: "assets/logos/genstar.png" },
  { company: "New Mountain Capital", short: "NMC", field: "Finance", subField: "Private Equity", logo: "assets/logos/newmountain.png" },

  // ── Private credit ───────────────────────────────────────────────────────
  { company: "Blue Owl Capital", short: "OWL", field: "Finance", subField: "Private Credit", logo: "assets/logos/blueowl.png" },
  { company: "Sixth Street Partners", short: "6TH", field: "Finance", subField: "Private Credit", logo: "assets/logos/sixthstreet.png" },
  { company: "Golub Capital", short: "GOLUB", field: "Finance", subField: "Private Credit", logo: "assets/logos/golub.png" },
  { company: "Monroe Capital", short: "MRCC", field: "Finance", subField: "Private Credit", logo: "assets/logos/monroe.png" },
  { company: "Antares Capital", short: "ANT", field: "Finance", subField: "Private Credit", logo: "assets/logos/antares.png" },
  { company: "Prospect Capital", short: "PSEC", field: "Finance", subField: "Private Credit", logo: "assets/logos/prospect.png" },
  { company: "FS Investments", short: "FS", field: "Finance", subField: "Private Credit", logo: "assets/logos/fsinvestments.png" },
  { company: "Benefit Street Partners", short: "BSP", field: "Finance", subField: "Private Credit", logo: "assets/logos/benefitstreet.png" },
  { company: "LoanCore Capital", short: "LC2", field: "Finance", subField: "Private Credit", logo: "assets/logos/loancore.png" },

  // ── Technology ───────────────────────────────────────────────────────────
  { company: "Microsoft", short: "MSFT", logoClass: "tech", field: "Technology", logo: "assets/logos/microsoft2.png" },
  { company: "Meta", short: "META", logoClass: "tech", field: "Technology", logo: "assets/logos/meta.png" },
  { company: "Netflix", short: "NFLX", logoClass: "tech", field: "Technology", logo: "assets/logos/netflix.png" },
  { company: "NVIDIA", short: "NVDA", logoClass: "tech", field: "Technology", logo: "assets/logos/nvidia.png" },
  { company: "Tesla", short: "TSLA", logoClass: "tech", field: "Technology", logo: "assets/logos/tesla.png" },
  { company: "Adobe", short: "ADBE", logoClass: "tech", field: "Technology", logo: "assets/logos/adobe2.png" },
  { company: "Salesforce", short: "CRM", logoClass: "tech", field: "Technology", logo: "assets/logos/salesforce.png" },
  { company: "Oracle", short: "ORCL", logoClass: "tech", field: "Technology", logo: "assets/logos/oracle.png" },
  { company: "IBM", short: "IBM", logoClass: "tech", field: "Technology", logo: "assets/logos/ibm.png" },
  { company: "Intel", short: "INTC", logoClass: "tech", field: "Technology", logo: "assets/logos/intel.png" },
  { company: "Qualcomm", short: "QCOM", logoClass: "tech", field: "Technology", logo: "assets/logos/qualcomm.png" },
  { company: "Uber", short: "UBER", logoClass: "tech", field: "Technology", logo: "assets/logos/uber.png" },
  { company: "Airbnb", short: "ABNB", logoClass: "tech", field: "Technology", logo: "assets/logos/airbnb.png" },
  { company: "Snap", short: "SNAP", logoClass: "tech", field: "Technology", logo: "assets/logos/snap.png" },
  { company: "Spotify", short: "SPOT", logoClass: "tech", field: "Technology", logo: "assets/logos/spotify2.png" },
  { company: "ServiceNow", short: "NOW", logoClass: "tech", field: "Technology", logo: "assets/logos/servicenow.png" },
  { company: "Workday", short: "WDAY", logoClass: "tech", field: "Technology", logo: "assets/logos/workdayinc.png" },
  { company: "Atlassian", short: "TEAM", logoClass: "tech", field: "Technology", logo: "assets/logos/atlassian.png" },
  { company: "Snowflake", short: "SNOW", logoClass: "tech", field: "Technology", logo: "assets/logos/snowflake.png" },
  { company: "CrowdStrike", short: "CRWD", logoClass: "tech", field: "Technology", logo: "assets/logos/crowdstrike.png" },
  { company: "Palo Alto Networks", short: "PANW", logoClass: "tech", field: "Technology", logo: "assets/logos/paloalto.png" },

  // ── Consulting ───────────────────────────────────────────────────────────
  { company: "Deloitte", short: "DEL", logoClass: "consult", field: "Consulting", subField: "Big 4", logo: "assets/logos/deloitte2.png" },
  { company: "EY", short: "EY", logoClass: "consult", field: "Consulting", subField: "Big 4", logo: "assets/logos/ey.png" },
  { company: "KPMG", short: "KPMG", logoClass: "consult", field: "Consulting", subField: "Big 4", logo: "assets/logos/kpmg.png" },
  { company: "Accenture", short: "ACN", logoClass: "consult", field: "Consulting", subField: "Tech Consulting", logo: "assets/logos/accenture.png" },
  { company: "Capgemini", short: "CAP", logoClass: "consult", field: "Consulting", subField: "Tech Consulting", logo: "assets/logos/capgemini.png" },
  { company: "Cognizant", short: "CTSH", logoClass: "consult", field: "Consulting", subField: "Tech Consulting", logo: "assets/logos/cognizant.png" },
  { company: "Slalom", short: "SLA", logoClass: "consult", field: "Consulting", subField: "Tech Consulting", logo: "assets/logos/slalom.png" },
  { company: "West Monroe", short: "WM", logoClass: "consult", field: "Consulting", subField: "Tech Consulting", logo: "assets/logos/westmonroe.png" },
  { company: "Kearney", short: "ATK", logoClass: "consult", field: "Consulting", subField: "Strategy", logo: "assets/logos/kearney.png" },
  { company: "L.E.K. Consulting", short: "LEK", logoClass: "consult", field: "Consulting", subField: "Strategy", logo: "assets/logos/lek.png" },
  { company: "Strategy& (PwC)", short: "S&", logoClass: "consult", field: "Consulting", subField: "Strategy", logo: "assets/logos/strategyand.png" },
  { company: "Roland Berger", short: "RB", logoClass: "consult", field: "Consulting", subField: "Strategy", logo: "assets/logos/rolandberger.png" },
  { company: "Booz Allen Hamilton", short: "BAH", logoClass: "consult", field: "Consulting", subField: "Strategy", logo: "assets/logos/boozallen.png" },
  { company: "Alvarez & Marsal", short: "A&M", logoClass: "consult", field: "Consulting", logo: "assets/logos/alvarezmarsal.png" },
  { company: "FTI Consulting", short: "FTI", logoClass: "consult", field: "Consulting", logo: "assets/logos/fti.png" },
  { company: "Huron", short: "HRN", logoClass: "consult", field: "Consulting", logo: "assets/logos/huron.png" },
  { company: "Guidehouse", short: "GH", logoClass: "consult", field: "Consulting", logo: "assets/logos/guidehouse.png" },
  { company: "ZS Associates", short: "ZS", logoClass: "consult", field: "Consulting", logo: "assets/logos/zs.png" },

  // ── Healthcare / Pharma ──────────────────────────────────────────────────
  { company: "Pfizer", short: "PFE", logoClass: "health", field: "Healthcare", logo: "assets/logos/pfizer2.png" },
  { company: "Johnson & Johnson", short: "JNJ", logoClass: "health", field: "Healthcare", logo: "assets/logos/jnj.png" },
  { company: "Merck", short: "MRK", logoClass: "health", field: "Healthcare", logo: "assets/logos/merck.png" },
  { company: "Moderna", short: "MRNA", logoClass: "health", field: "Healthcare", logo: "assets/logos/moderna2.png" },
  { company: "Eli Lilly", short: "LLY", logoClass: "health", field: "Healthcare", logo: "assets/logos/lilly.png" },
  { company: "AbbVie", short: "ABBV", logoClass: "health", field: "Healthcare", logo: "assets/logos/abbvie.png" },
  { company: "Amgen", short: "AMGN", logoClass: "health", field: "Healthcare", logo: "assets/logos/amgen.png" },
  { company: "Gilead Sciences", short: "GILD", logoClass: "health", field: "Healthcare", logo: "assets/logos/gilead.png" },
  { company: "Bristol Myers Squibb", short: "BMY", logoClass: "health", field: "Healthcare", logo: "assets/logos/bms.png" },
  { company: "Regeneron", short: "REGN", logoClass: "health", field: "Healthcare", logo: "assets/logos/regeneron.png" },
  { company: "Vertex Pharmaceuticals", short: "VRTX", logoClass: "health", field: "Healthcare", logo: "assets/logos/vertex.png" },
  { company: "Novartis", short: "NVS", logoClass: "health", field: "Healthcare", logo: "assets/logos/novartis.png" },
  { company: "AstraZeneca", short: "AZN", logoClass: "health", field: "Healthcare", logo: "assets/logos/astrazeneca.png" },
  { company: "GSK", short: "GSK", logoClass: "health", field: "Healthcare", logo: "assets/logos/gsk.png" },
  { company: "Genentech", short: "DNA2", logoClass: "health", field: "Healthcare", logo: "assets/logos/genentech.png" },
  { company: "UnitedHealth Group", short: "UNH", logoClass: "health", field: "Healthcare", logo: "assets/logos/unitedhealth.png" },
  { company: "CVS Health", short: "CVS", logoClass: "health", field: "Healthcare", logo: "assets/logos/cvshealth.png" },
  { company: "Cigna", short: "CI", logoClass: "health", field: "Healthcare", logo: "assets/logos/cigna.png" },
  { company: "Humana", short: "HUM", logoClass: "health", field: "Healthcare", logo: "assets/logos/humana.png" },
  { company: "Mayo Clinic", short: "MAYO", logoClass: "health", field: "Healthcare", logo: "assets/logos/mayoclinic2.png" },
  { company: "Cleveland Clinic", short: "CC", logoClass: "health", field: "Healthcare", logo: "assets/logos/clevelandclinic.png" },

  // ── Law ──────────────────────────────────────────────────────────────────
  { company: "Kirkland & Ellis", short: "K&E", logoClass: "law", field: "Law", logo: "assets/logos/kirkland.png" },
  { company: "Latham & Watkins", short: "L&W", logoClass: "law", field: "Law", logo: "assets/logos/lathamwatkins.png" },
  { company: "Skadden", short: "SKAD", logoClass: "law", field: "Law", logo: "assets/logos/skadden.png" },
  { company: "Sullivan & Cromwell", short: "S&C", logoClass: "law", field: "Law", logo: "assets/logos/sullcrom.png" },
  { company: "Cravath", short: "CSM", logoClass: "law", field: "Law", logo: "assets/logos/cravath.png" },
  { company: "Davis Polk", short: "DPW", logoClass: "law", field: "Law", logo: "assets/logos/davispolk.png" },
  { company: "Wachtell Lipton", short: "WLRK", logoClass: "law", field: "Law", logo: "assets/logos/wachtell.png" },
  { company: "Simpson Thacher", short: "STB", logoClass: "law", field: "Law", logo: "assets/logos/simpsonthacher.png" },
  { company: "Gibson Dunn", short: "GD", logoClass: "law", field: "Law", logo: "assets/logos/gibsondunn.png" },
  { company: "Sidley Austin", short: "SID", logoClass: "law", field: "Law", logo: "assets/logos/sidley.png" },
  { company: "White & Case", short: "W&C", logoClass: "law", field: "Law", logo: "assets/logos/whitecase.png" },
  { company: "Paul, Weiss", short: "PW", logoClass: "law", field: "Law", logo: "assets/logos/paulweiss.png" },

  // ── Government & Policy ───────────────────────────────────────────────────
  { company: "U.S. Department of State", short: "DOS", logoClass: "gov", field: "Government", logo: "assets/logos/state.png" },
  { company: "CIA", short: "CIA", logoClass: "gov", field: "Government", logo: "assets/logos/cia.png" },
  { company: "FBI", short: "FBI", logoClass: "gov", field: "Government", logo: "assets/logos/fbi.png" },
  { company: "NASA", short: "NASA", logoClass: "gov", field: "Government", logo: "assets/logos/nasa2.png" },
  { company: "Federal Reserve", short: "FED", logoClass: "gov", field: "Government", logo: "assets/logos/fed.png" },
  { company: "SEC", short: "SEC", logoClass: "gov", field: "Government", logo: "assets/logos/sec.png" },
  { company: "World Bank", short: "WB", logoClass: "gov", field: "Government", logo: "assets/logos/worldbank.png" },
  { company: "IMF", short: "IMF", logoClass: "gov", field: "Government", logo: "assets/logos/imf.png" },
  { company: "United Nations", short: "UN", logoClass: "gov", field: "Government", logo: "assets/logos/un.png" },
  { company: "Brookings Institution", short: "BROOK", logoClass: "gov", field: "Government", logo: "assets/logos/brookings.png" },
  { company: "RAND Corporation", short: "RAND", logoClass: "gov", field: "Government", logo: "assets/logos/rand.png" },

  // ── Media & Entertainment ────────────────────────────────────────────────
  { company: "The Walt Disney Company", short: "DIS", logoClass: "media", field: "Media", logo: "assets/logos/disney2.png" },
  { company: "NBCUniversal", short: "NBCU", logoClass: "media", field: "Media", logo: "assets/logos/nbcuni.png" },
  { company: "Warner Bros. Discovery", short: "WBD", logoClass: "media", field: "Media", logo: "assets/logos/wbd.png" },
  { company: "Paramount", short: "PARA", logoClass: "media", field: "Media", logo: "assets/logos/paramount.png" },
  { company: "Sony Pictures", short: "SONY", logoClass: "media", field: "Media", logo: "assets/logos/sonypictures.png" },
  { company: "The New York Times", short: "NYT", logoClass: "media", field: "Media", logo: "assets/logos/nyt.png" },
  { company: "Condé Nast", short: "CN", logoClass: "media", field: "Media", logo: "assets/logos/condenast.png" },
  { company: "Bloomberg", short: "BBG", logoClass: "media", field: "Media", logo: "assets/logos/bloomberg.png" },
  { company: "Hearst", short: "HRST", logoClass: "media", field: "Media", logo: "assets/logos/hearst.png" },
  { company: "Live Nation", short: "LYV", logoClass: "media", field: "Media", logo: "assets/logos/livenation.png" },

  // ── Marketing & Advertising ──────────────────────────────────────────────
  { company: "Ogilvy", short: "OGV", logoClass: "mkt", field: "Marketing", logo: "assets/logos/ogilvy.png" },
  { company: "WPP", short: "WPP", logoClass: "mkt", field: "Marketing", logo: "assets/logos/wpp.png" },
  { company: "Publicis Groupe", short: "PUB", logoClass: "mkt", field: "Marketing", logo: "assets/logos/publicis.png" },
  { company: "Omnicom", short: "OMC", logoClass: "mkt", field: "Marketing", logo: "assets/logos/omnicom.png" },
  { company: "Edelman", short: "EDL", logoClass: "mkt", field: "Marketing", logo: "assets/logos/edelman.png" },
  { company: "Wieden+Kennedy", short: "W+K", logoClass: "mkt", field: "Marketing", logo: "assets/logos/wk.png" },
  { company: "Dentsu", short: "DNTS", logoClass: "mkt", field: "Marketing", logo: "assets/logos/dentsu.png" },
  { company: "Interpublic (IPG)", short: "IPG", logoClass: "mkt", field: "Marketing", logo: "assets/logos/ipg.png" },

  // ── Consumer & Retail (CPG) ──────────────────────────────────────────────
  { company: "Procter & Gamble", short: "PG", logoClass: "consumer", field: "Consumer", logo: "assets/logos/pg.png" },
  { company: "Unilever", short: "UL", logoClass: "consumer", field: "Consumer", logo: "assets/logos/unilever.png" },
  { company: "Coca-Cola", short: "KO", logoClass: "consumer", field: "Consumer", logo: "assets/logos/cocacola.png" },
  { company: "PepsiCo", short: "PEP", logoClass: "consumer", field: "Consumer", logo: "assets/logos/pepsico.png" },
  { company: "Nike", short: "NKE", logoClass: "consumer", field: "Consumer", logo: "assets/logos/nike.png" },
  { company: "Nestlé", short: "NSRGY", logoClass: "consumer", field: "Consumer", logo: "assets/logos/nestle.png" },
  { company: "L'Oréal", short: "LRLCY", logoClass: "consumer", field: "Consumer", logo: "assets/logos/loreal.png" },
  { company: "Estée Lauder", short: "EL", logoClass: "consumer", field: "Consumer", logo: "assets/logos/esteelauder.png" },
  { company: "Target", short: "TGT", logoClass: "consumer", field: "Consumer", logo: "assets/logos/target.png" },
  { company: "Mondelez", short: "MDLZ", logoClass: "consumer", field: "Consumer", logo: "assets/logos/mondelez.png" },
  { company: "Kraft Heinz", short: "KHC", logoClass: "consumer", field: "Consumer", logo: "assets/logos/kraftheinz.png" },
  { company: "Colgate-Palmolive", short: "CL", logoClass: "consumer", field: "Consumer", logo: "assets/logos/colgate.png" },

  // ── Engineering / Aerospace / Energy ─────────────────────────────────────
  { company: "Boeing", short: "BA", logoClass: "eng", field: "Engineering", logo: "assets/logos/boeing.png" },
  { company: "Lockheed Martin", short: "LMT", logoClass: "eng", field: "Engineering", logo: "assets/logos/lockheed.png" },
  { company: "SpaceX", short: "SPX", logoClass: "eng", field: "Engineering", logo: "assets/logos/spacex.png" },
  { company: "Northrop Grumman", short: "NOC", logoClass: "eng", field: "Engineering", logo: "assets/logos/northrop.png" },
  { company: "RTX (Raytheon)", short: "RTX", logoClass: "eng", field: "Engineering", logo: "assets/logos/rtx.png" },
  { company: "General Electric", short: "GE", logoClass: "eng", field: "Engineering", logo: "assets/logos/ge.png" },
  { company: "Caterpillar", short: "CAT", logoClass: "eng", field: "Engineering", logo: "assets/logos/caterpillar.png" },
  { company: "ExxonMobil", short: "XOM", logoClass: "eng", field: "Engineering", logo: "assets/logos/exxonmobil.png" },
  { company: "Chevron", short: "CVX", logoClass: "eng", field: "Engineering", logo: "assets/logos/chevron.png" },
  { company: "Ford", short: "F", logoClass: "eng", field: "Engineering", logo: "assets/logos/ford.png" },
  { company: "General Motors", short: "GM", logoClass: "eng", field: "Engineering", logo: "assets/logos/gm.png" },

  // ── Science & Research ───────────────────────────────────────────────────
  { company: "NIH", short: "NIH", logoClass: "sci", field: "Science", logo: "assets/logos/nih.png" },
  { company: "Broad Institute", short: "BROAD", logoClass: "sci", field: "Science", logo: "assets/logos/broad.png" },
  { company: "Cold Spring Harbor Lab", short: "CSHL", logoClass: "sci", field: "Science", logo: "assets/logos/cshl.png" },
  { company: "Lawrence Berkeley Lab", short: "LBNL", logoClass: "sci", field: "Science", logo: "assets/logos/lbl.png" },
  { company: "Los Alamos Lab", short: "LANL", logoClass: "sci", field: "Science", logo: "assets/logos/lanl.png" },
  { company: "Howard Hughes (HHMI)", short: "HHMI", logoClass: "sci", field: "Science", logo: "assets/logos/hhmi.png" },

  // ── Nonprofit & Social Impact ────────────────────────────────────────────
  { company: "Teach For America", short: "TFA", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/tfa.png" },
  { company: "UNICEF", short: "UNICEF", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/unicef2.png" },
  { company: "American Red Cross", short: "ARC", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/redcross.png" },
  { company: "Gates Foundation", short: "GATES", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/gates.png" },
  { company: "Doctors Without Borders", short: "MSF", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/msf.png" },
  { company: "World Wildlife Fund", short: "WWF", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/wwf.png" },
  { company: "Habitat for Humanity", short: "HFH", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/habitat.png" },
  { company: "Peace Corps", short: "PC", logoClass: "npo", field: "Nonprofit", logo: "assets/logos/peacecorps.png" },

  // ── Education ────────────────────────────────────────────────────────────
  { company: "Chegg", short: "CHGG", logoClass: "edu", field: "Education", logo: "assets/logos/chegg.png" },
  { company: "Coursera", short: "COUR", logoClass: "edu", field: "Education", logo: "assets/logos/coursera.png" },
  { company: "Pearson", short: "PSO", logoClass: "edu", field: "Education", logo: "assets/logos/pearson.png" },
  { company: "2U", short: "TWOU", logoClass: "edu", field: "Education", logo: "assets/logos/2u.png" },

  // ── Sports ───────────────────────────────────────────────────────────────
  { company: "The Athletic", short: "ATH", logoClass: "media", field: "Sports", subField: "Sports Media" },
  { company: "ESPN", short: "ESPN", logoClass: "media", field: "Sports", subField: "Sports Media" },
  { company: "NBA", short: "NBA", logoClass: "media", field: "Sports", subField: "Teams & Leagues" },
  { company: "NFL", short: "NFL", logoClass: "media", field: "Sports", subField: "Teams & Leagues" },
  { company: "MLB", short: "MLB", logoClass: "media", field: "Sports", subField: "Teams & Leagues" },
  { company: "Fanatics", short: "FAN", logoClass: "consumer", field: "Sports", subField: "Sports Technology" },
  { company: "DraftKings", short: "DK", logoClass: "tech", field: "Sports", subField: "Sports Technology" },
  { company: "Wasserman", short: "WASS", logoClass: "mkt", field: "Sports", subField: "Sports Marketing" },

  // ── Real Estate ──────────────────────────────────────────────────────────
  { company: "VTS", short: "VTS", logoClass: "consumer", field: "Real Estate", subField: "Property Technology" },
  { company: "CBRE", short: "CBRE", logoClass: "consumer", field: "Real Estate", subField: "Brokerage" },
  { company: "JLL", short: "JLL", logoClass: "consumer", field: "Real Estate", subField: "Brokerage" },
  { company: "Cushman & Wakefield", short: "C&W", logoClass: "consumer", field: "Real Estate", subField: "Brokerage" },
  { company: "Prologis", short: "PLD", logoClass: "consumer", field: "Real Estate", subField: "Development" },
  { company: "Related Companies", short: "REL", logoClass: "consumer", field: "Real Estate", subField: "Development" },
  { company: "Zillow", short: "ZG", logoClass: "tech", field: "Real Estate", subField: "Property Technology" },
  { company: "Blackstone Real Estate", short: "BXRE", logoClass: "fin", field: "Real Estate", subField: "Investment" },

  // ── Live-feed companies (Ashby/SmartRecruiters, added Jul 2026) ──────────
  // These have verified live pipelines; cards show as awaiting until their
  // 2027 postings appear, then flip to the real listing automatically.
  { company: "OpenAI", short: "OAI", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Ramp", short: "RAMP", logoClass: "fin", field: "Finance", subField: "Fintech" },
  { company: "Notion", short: "NTN", logoClass: "tech", field: "Technology" },
  { company: "Linear", short: "LNR", logoClass: "tech", field: "Technology" },
  { company: "Vanta", short: "VNTA", logoClass: "tech", field: "Technology" },
  { company: "Replit", short: "RPLT", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Cohere", short: "CO", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Modal", short: "MODL", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Supabase", short: "SUPA", logoClass: "tech", field: "Technology" },
  { company: "ElevenLabs", short: "11L", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Cursor (Anysphere)", short: "CURS", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Sierra", short: "SIRA", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "Harvey", short: "HRVY", logoClass: "law", field: "Law", subField: "Legal Technology" },
  { company: "Writer", short: "WRTR", logoClass: "tech", field: "Technology", subField: "AI" },
  { company: "ServiceNow", short: "NOW", logoClass: "tech", field: "Technology" },
  { company: "Experian", short: "EXPN", logoClass: "fin", field: "Finance", subField: "Fintech" },
  { company: "Ubisoft", short: "UBI", logoClass: "tech", field: "Technology", subField: "Gaming" },
  { company: "Continental", short: "CONTI", logoClass: "eng", field: "Engineering", subField: "Automotive" },
];
